# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mangle_pb2 as mangle__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mangle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MangleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_stream(
                '/mangle.Mangle/Query',
                request_serializer=mangle__pb2.QueryRequest.SerializeToString,
                response_deserializer=mangle__pb2.QueryAnswer.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/mangle.Mangle/Update',
                request_serializer=mangle__pb2.UpdateRequest.SerializeToString,
                response_deserializer=mangle__pb2.UpdateAnswer.FromString,
                _registered_method=True)


class MangleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """The server answers a query with a stream of responses.
        It is possible that the list of results is empty.
        In case of errors, no answers are sent and a QueryError
        message is included in status response metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """The server updates its state with result of program.
        In case of errors, no update happens and an UpdateError
        message is included in status response metadata.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MangleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=mangle__pb2.QueryRequest.FromString,
                    response_serializer=mangle__pb2.QueryAnswer.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=mangle__pb2.UpdateRequest.FromString,
                    response_serializer=mangle__pb2.UpdateAnswer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mangle.Mangle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mangle.Mangle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Mangle(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mangle.Mangle/Query',
            mangle__pb2.QueryRequest.SerializeToString,
            mangle__pb2.QueryAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mangle.Mangle/Update',
            mangle__pb2.UpdateRequest.SerializeToString,
            mangle__pb2.UpdateAnswer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
