# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mangle.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mangle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmangle.proto\x12\x06mangle\".\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x0f\n\x07program\x18\x02 \x01(\t\" \n\rUpdateRequest\x12\x0f\n\x07program\x18\x02 \x01(\t\"\x19\n\nQueryError\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1a\n\x0bUpdateError\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1d\n\x0bQueryAnswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"*\n\x0cUpdateAnswer\x12\x1a\n\x12updated_predicates\x18\x02 \x03(\t2u\n\x06Mangle\x12\x34\n\x05Query\x12\x14.mangle.QueryRequest\x1a\x13.mangle.QueryAnswer0\x01\x12\x35\n\x06Update\x12\x15.mangle.UpdateRequest\x1a\x14.mangle.UpdateAnswerB+Z)github.com/burakemir/mangle-service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mangle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/burakemir/mangle-service/proto'
  _globals['_QUERYREQUEST']._serialized_start=24
  _globals['_QUERYREQUEST']._serialized_end=70
  _globals['_UPDATEREQUEST']._serialized_start=72
  _globals['_UPDATEREQUEST']._serialized_end=104
  _globals['_QUERYERROR']._serialized_start=106
  _globals['_QUERYERROR']._serialized_end=131
  _globals['_UPDATEERROR']._serialized_start=133
  _globals['_UPDATEERROR']._serialized_end=159
  _globals['_QUERYANSWER']._serialized_start=161
  _globals['_QUERYANSWER']._serialized_end=190
  _globals['_UPDATEANSWER']._serialized_start=192
  _globals['_UPDATEANSWER']._serialized_end=234
  _globals['_MANGLE']._serialized_start=236
  _globals['_MANGLE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
